version: '3.7'

services:
  db:
    build: ./docker/db
    image: registry.gitlab.com/frysztak/dashchart/db:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
  app:
    build: ./
    image: registry.gitlab.com/frysztak/dashchart/app:latest
    ports:
      - 3000:3000
