version: '3.7'

services:
  db:
    build: ./docker/db
    image: registry.gitlab.com/frysztak/dashchart/db:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    networks:
      - proxy
    restart: unless-stopped
  app:
    build: ./
    image: registry.gitlab.com/frysztak/dashchart/app:latest
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=dashchart.frysztak.net
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=dashchart.frysztak.net
      - LETSENCRYPT_EMAIL=sebastian.frysztak@gmail.com
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy
