import { styled } from '../../../config/Theme';
import { keyframes } from 'styled-components';

const RotateKeyframes = keyframes`
/* ----------------------------------------------
 * Generated by Animista on 2020-5-14 20:33:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
`;

export const Rotate = styled.div`
  &:hover {
    animation: ${RotateKeyframes} 0.6s ease-in-out both;
  }
`;
