import { styled } from '../../../config/Theme';
import { keyframes } from 'styled-components';

const WobbleKeyframes = keyframes`
/* ----------------------------------------------
 * Generated by Animista on 2020-5-14 20:24:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation wobble-hor-top
 * ----------------------------------------
 */
  0%,
  100% {
    transform: translateX(0%);
    transform-origin: 50% 50%;
  }
  15% {
    transform: translateX(-15px) rotate(6deg);
  }
  30% {
    transform: translateX(7.5px) rotate(-6deg);
  }
  45% {
    transform: translateX(-7.5px) rotate(3.6deg);
  }
  60% {
    transform: translateX(4.5px) rotate(-2.4deg);
  }
  75% {
    transform: translateX(-3px) rotate(1.2deg);
  }
`;

export const Wobble = styled.div`
  &:hover {
    animation: ${WobbleKeyframes} 0.5s both;
  }
`;
